cls
REM set CPP_PRJ=%1
REM echo BUILD '%CPP_PRJ%'
REM set pwd=%cd%
REM REM 21.4.7075529
REM set ANDROID_NDK_HOME=C:\Android\Sdk\ndk\25.1.8937393
REM set VCPKG_ROOT=C:\pro\vcpkg
REM 
REM set CPP_ANDROID_ROOT=C:\Android
REM set CPP_ANDROID_BLD=%CPP_ANDROID_ROOT%\bld
REM set CPP_ANDROID_REPO=%CPP_ANDROID_ROOT%\repo
REM set CPP_ANDROID_ABI=x86_64
REM set CPP_ANDROID_API=30
REM mkdir %CPP_ANDROID_REPO%\%PRJ%
REM mkdir %CPP_ANDROID_BLD%\%PRJ%\Debug
REM mkdir %CPP_ANDROID_BLD%\%PRJ%\Release
REM 
REM 
REM set CPP_TYPE=Debug
REM cd C:\Android\bld\%PRJ%\%CMP_TYPE%
REM 
REM cmake -DVCPKG_TARGET_TRIPLET=x64-android-30 -DANDROID_PLATFORM=android-%CPP_ANDROID_API% -Wno-dev -DCMAKE_FIND_DEBUG_MODE=OFF -DCMAKE_INSTALL_PREFIX=%CPP_ANDROID_REPO%/%CPP_PRJ% -DCMAKE_TOOLCHAIN_FILE=C:/pro/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%/build/cmake/android.toolchain.cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=%CPP_TYPE% -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=lib/%CPP_ANDROID_ABI%/%CPP_TYPE% -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=lib/%CPP_ANDROID_ABI%/%CPP_TYPE% -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin/%CPP_ANDROID_ABI%/%CPP_TYPE% -DCMAKE_DEBUG_POSTFIX=_d -DVCPKG_OVERLAY_PORTS=C:/pro/github/onbings-vcpkg-registry/ports C:\pro\github\vcpkg-packaging-env
REM 
REM cmake --build . --config %CMP_TYPE%
REM cmake --install . --prefix C:/Android/repo/%PRJ%
REM 
REM cd %pwd%




REM cls
REM set pwd=%cd%
REM set ANDROID_NDK_HOME=C:\Android\Sdk\ndk\25.1.8937393
REM set VCPKG_ROOT=C:\pro\vcpkg
REM 
REM set CPP_ANDROID_REPO_BLD_ROOT=C:\Android
REM set CPP_ANDROID_PRJ=vcpkg-packaging-env
REM 
REM set CPP_TYPE=Debug
REM mkdir %CPP_ANDROID_REPO_BLD_ROOT%\bld\%CPP_ANDROID_PRJ%\%CPP_TYPE%
REM cd %CPP_ANDROID_REPO_BLD_ROOT%\bld\%CPP_ANDROID_PRJ%\%CPP_TYPE%
REM 
REM cmake -DVCPKG_CMAKE_SYSTEM_VERSION=30 -DANDROID_PLATFORM=android-30 -DCPP_ANDROID_PRJ=%CPP_ANDROID_PRJ% -DCPP_ANDROID_ABI=x86_64 -DANDROID_NDK_HOME=C:\Android\Sdk\ndk\25.1.8937393 -DVCPKG_ROOT=C:\pro\vcpkg -DCPP_ANDROID_REPO_BLD_ROOT=%CPP_ANDROID_REPO_BLD_ROOT% -Wno-dev -DCMAKE_FIND_DEBUG_MODE=OFF -DCMAKE_TOOLCHAIN_FILE=C:/pro/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%/build/cmake/android.toolchain.cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=%CPP_TYPE% -DCMAKE_DEBUG_POSTFIX=_d -DVCPKG_OVERLAY_PORTS=C:/pro/github/onbings-vcpkg-registry/ports C:\pro\github\%CPP_ANDROID_PRJ%

rem cmake -DANDROID_PLATFORM=android-30 -DCPP_ANDROID_PRJ=%CPP_ANDROID_PRJ% -DCPP_ANDROID_ABI=x86_64 -DANDROID_NDK_HOME=C:\Android\Sdk\ndk\25.1.8937393 -DVCPKG_ROOT=C:\pro\vcpkg -DCPP_ANDROID_REPO_BLD_ROOT=%CPP_ANDROID_REPO_BLD_ROOT% -Wno-dev -DCMAKE_FIND_DEBUG_MODE=OFF -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=%CPP_TYPE% -DCMAKE_DEBUG_POSTFIX=_d -DVCPKG_OVERLAY_PORTS=C:/pro/github/onbings-vcpkg-registry/ports C:\pro\github\%CPP_ANDROID_PRJ%

cmake -DVCPKG_TARGET_TRIPLET=x64-android-30 -DCMAKE_TOOLCHAIN_FILE=C:/pro/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%/build/cmake/android.toolchain.cmake -DBUILD_SHARED_LIBS=ON -DVCPKG_OVERLAY_PORTS=C:/pro/github/onbings-vcpkg-registry/ports C:\pro\github\%CPP_ANDROID_PRJ%


REM cmake --build . --config %CPP_TYPE%
REM cmake --install . --prefix %CPP_ANDROID_REPO_BLD_ROOT%\repo\%CPP_ANDROID_PRJ%\%CPP_TYPE%

cd %pwd%

rem C:\Android\Sdk\ndk\25.1.8937393/build/cmake/android.toolchain.cmake








REM cls
REM set pwd=%cd%
REM 
REM set CPP_ANDROID_REPO_BLD_ROOT=C:\Android
REM set CPP_ANDROID_PRJ=vcpkg-packaging-env
REM 
REM set CPP_TYPE=Debug
REM cd %CPP_ANDROID_REPO_BLD_ROOT%\bld\%CPP_ANDROID_PRJ%\%CPP_TYPE%
REM 
REM cmake -DANDROID_PLATFORM=android-30 -DCPP_ANDROID_PRJ=%CPP_ANDROID_PRJ% -DCPP_ANDROID_ABI=x86_64 -DANDROID_NDK_HOME=C:\Android\Sdk\ndk\25.1.8937393 -DVCPKG_ROOT=C:\pro\vcpkg -DCPP_ANDROID_REPO_BLD_ROOT=%CPP_ANDROID_REPO_BLD_ROOT% -Wno-dev -DCMAKE_FIND_DEBUG_MODE=OFF -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=%CPP_TYPE% -DCMAKE_DEBUG_POSTFIX=_d -DVCPKG_OVERLAY_PORTS=C:/pro/github/onbings-vcpkg-registry/ports C:\pro\github\%CPP_ANDROID_PRJ%
REM 
REM cmake --build . --config %CPP_TYPE%
REM cmake --install . --prefix %CPP_ANDROID_REPO_BLD_ROOT%\repo\%CPP_ANDROID_PRJ%\%CPP_TYPE%
REM 
REM cd %pwd%

